# Generated by Trivx AI
# Provider: aws

{
  "terraform": {
    "required_version": ">= 1.0",
    "required_providers": {
      "aws": {
        "source": "hashicorp/aws",
        "version": "~> 5.0"
      }
    }
  },
  "provider": {
    "aws": {
      "region": "us-east-1"
    }
  },
  "locals": {
    "project_name": "react-app",
    "environment": "production",
    "availability_zones": [
      "us-east-1a",
      "us-east-1b"
    ],
    "common_tags": {
      "Project": "react-app",
      "Environment": "production",
      "ManagedBy": "Terraform"
    }
  },
  "data": {
    "aws_caller_identity": {
      "current": {}
    }
  },
  "resource": {
    "aws_vpc": {
      "main": {
        "cidr_block": "10.0.0.0/16",
        "enable_dns_hostnames": true,
        "enable_dns_support": true,
        "tags": {
          "Name": "${local.project_name}-vpc",
          "Environment": "${local.environment}"
        }
      }
    },
    "aws_subnet": {
      "public_1": {
        "vpc_id": "${aws_vpc.main.id}",
        "cidr_block": "10.0.1.0/24",
        "availability_zone": "${local.availability_zones[0]}",
        "map_public_ip_on_launch": true,
        "tags": {
          "Name": "${local.project_name}-public-subnet-1",
          "Type": "Public"
        }
      },
      "public_2": {
        "vpc_id": "${aws_vpc.main.id}",
        "cidr_block": "10.0.2.0/24",
        "availability_zone": "${local.availability_zones[1]}",
        "map_public_ip_on_launch": true,
        "tags": {
          "Name": "${local.project_name}-public-subnet-2",
          "Type": "Public"
        }
      },
      "private_1": {
        "vpc_id": "${aws_vpc.main.id}",
        "cidr_block": "10.0.10.0/24",
        "availability_zone": "${local.availability_zones[0]}",
        "tags": {
          "Name": "${local.project_name}-private-subnet-1",
          "Type": "Private"
        }
      },
      "private_2": {
        "vpc_id": "${aws_vpc.main.id}",
        "cidr_block": "10.0.11.0/24",
        "availability_zone": "${local.availability_zones[1]}",
        "tags": {
          "Name": "${local.project_name}-private-subnet-2",
          "Type": "Private"
        }
      }
    },
    "aws_internet_gateway": {
      "main": {
        "vpc_id": "${aws_vpc.main.id}",
        "tags": {
          "Name": "${local.project_name}-igw"
        }
      }
    },
    "aws_eip": {
      "nat_1": {
        "domain": "vpc",
        "tags": {
          "Name": "${local.project_name}-nat-eip-1"
        }
      },
      "nat_2": {
        "domain": "vpc",
        "tags": {
          "Name": "${local.project_name}-nat-eip-2"
        }
      }
    },
    "aws_nat_gateway": {
      "nat_1": {
        "allocation_id": "${aws_eip.nat_1.id}",
        "subnet_id": "${aws_subnet.public_1.id}",
        "tags": {
          "Name": "${local.project_name}-nat-gateway-1"
        },
        "depends_on": [
          "aws_internet_gateway.main"
        ]
      },
      "nat_2": {
        "allocation_id": "${aws_eip.nat_2.id}",
        "subnet_id": "${aws_subnet.public_2.id}",
        "tags": {
          "Name": "${local.project_name}-nat-gateway-2"
        },
        "depends_on": [
          "aws_internet_gateway.main"
        ]
      }
    },
    "aws_route_table": {
      "public": {
        "vpc_id": "${aws_vpc.main.id}",
        "route": [
          {
            "cidr_block": "0.0.0.0/0",
            "gateway_id": "${aws_internet_gateway.main.id}"
          }
        ],
        "tags": {
          "Name": "${local.project_name}-public-rt"
        }
      },
      "private_1": {
        "vpc_id": "${aws_vpc.main.id}",
        "route": [
          {
            "cidr_block": "0.0.0.0/0",
            "nat_gateway_id": "${aws_nat_gateway.nat_1.id}"
          }
        ],
        "tags": {
          "Name": "${local.project_name}-private-rt-1"
        }
      },
      "private_2": {
        "vpc_id": "${aws_vpc.main.id}",
        "route": [
          {
            "cidr_block": "0.0.0.0/0",
            "nat_gateway_id": "${aws_nat_gateway.nat_2.id}"
          }
        ],
        "tags": {
          "Name": "${local.project_name}-private-rt-2"
        }
      }
    },
    "aws_route_table_association": {
      "public_1": {
        "subnet_id": "${aws_subnet.public_1.id}",
        "route_table_id": "${aws_route_table.public.id}"
      },
      "public_2": {
        "subnet_id": "${aws_subnet.public_2.id}",
        "route_table_id": "${aws_route_table.public.id}"
      },
      "private_1": {
        "subnet_id": "${aws_subnet.private_1.id}",
        "route_table_id": "${aws_route_table.private_1.id}"
      },
      "private_2": {
        "subnet_id": "${aws_subnet.private_2.id}",
        "route_table_id": "${aws_route_table.private_2.id}"
      }
    },
    "aws_security_group": {
      "alb": {
        "name": "${local.project_name}-alb-sg",
        "description": "Security group for Application Load Balancer",
        "vpc_id": "${aws_vpc.main.id}",
        "ingress": [
          {
            "description": "HTTP from Internet",
            "from_port": 80,
            "to_port": 80,
            "protocol": "tcp",
            "cidr_blocks": [
              "0.0.0.0/0"
            ]
          },
          {
            "description": "HTTPS from Internet",
            "from_port": 443,
            "to_port": 443,
            "protocol": "tcp",
            "cidr_blocks": [
              "0.0.0.0/0"
            ]
          }
        ],
        "egress": [
          {
            "description": "Allow all outbound",
            "from_port": 0,
            "to_port": 0,
            "protocol": "-1",
            "cidr_blocks": [
              "0.0.0.0/0"
            ]
          }
        ],
        "tags": {
          "Name": "${local.project_name}-alb-sg"
        }
      },
      "ecs": {
        "name": "${local.project_name}-ecs-sg",
        "description": "Security group for ECS tasks",
        "vpc_id": "${aws_vpc.main.id}",
        "ingress": [
          {
            "description": "Allow traffic from ALB",
            "from_port": 80,
            "to_port": 80,
            "protocol": "tcp",
            "security_groups": [
              "${aws_security_group.alb.id}"
            ]
          },
          {
            "description": "Allow traffic from ALB on port 3000",
            "from_port": 3000,
            "to_port": 3000,
            "protocol": "tcp",
            "security_groups": [
              "${aws_security_group.alb.id}"
            ]
          }
        ],
        "egress": [
          {
            "description": "Allow all outbound",
            "from_port": 0,
            "to_port": 0,
            "protocol": "-1",
            "cidr_blocks": [
              "0.0.0.0/0"
            ]
          }
        ],
        "tags": {
          "Name": "${local.project_name}-ecs-sg"
        }
      }
    },
    "aws_ecr_repository": {
      "main": {
        "name": "${local.project_name}",
        "image_tag_mutability": "MUTABLE",
        "image_scanning_configuration": {
          "scan_on_push": true
        },
        "tags": {
          "Name": "${local.project_name}-ecr"
        }
      }
    },
    "aws_ecr_lifecycle_policy": {
      "main": {
        "repository": "${aws_ecr_repository.main.name}",
        "policy": "{\"rules\":[{\"rulePriority\":1,\"description\":\"Keep last 10 images\",\"selection\":{\"tagStatus\":\"any\",\"countType\":\"imageCountMoreThan\",\"countNumber\":10},\"action\":{\"type\":\"expire\"}}]}"
      }
    },
    "aws_cloudwatch_log_group": {
      "ecs": {
        "name": "/ecs/${local.project_name}",
        "retention_in_days": 30,
        "tags": {
          "Name": "${local.project_name}-logs"
        }
      }
    },
    "aws_iam_role": {
      "ecs_execution_role": {
        "name": "${local.project_name}-ecs-execution-role",
        "assume_role_policy": "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"ecs-tasks.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}",
        "tags": {
          "Name": "${local.project_name}-ecs-execution-role"
        }
      },
      "ecs_task_role": {
        "name": "${local.project_name}-ecs-task-role",
        "assume_role_policy": "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"ecs-tasks.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}",
        "tags": {
          "Name": "${local.project_name}-ecs-task-role"
        }
      }
    },
    "aws_iam_role_policy_attachment": {
      "ecs_execution_role_policy": {
        "role": "${aws_iam_role.ecs_execution_role.name}",
        "policy_arn": "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
      },
      "ecs_execution_role_ecr": {
        "role": "${aws_iam_role.ecs_execution_role.name}",
        "policy_arn": "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
      }
    },
    "aws_iam_role_policy": {
      "ecs_task_cloudwatch": {
        "name": "cloudwatch-logs-policy",
        "role": "${aws_iam_role.ecs_task_role.id}",
        "policy": "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":[\"logs:CreateLogGroup\",\"logs:CreateLogStream\",\"logs:PutLogEvents\"],\"Resource\":\"*\"}]}"
      }
    },
    "aws_ecs_cluster": {
      "main": {
        "name": "${local.project_name}-cluster",
        "setting": [
          {
            "name": "containerInsights",
            "value": "enabled"
          }
        ],
        "tags": {
          "Name": "${local.project_name}-cluster"
        }
      }
    },
    "aws_ecs_task_definition": {
      "main": {
        "family": "${local.project_name}",
        "network_mode": "awsvpc",
        "requires_compatibilities": [
          "FARGATE"
        ],
        "cpu": "512",
        "memory": "1024",
        "execution_role_arn": "${aws_iam_role.ecs_execution_role.arn}",
        "task_role_arn": "${aws_iam_role.ecs_task_role.arn}",
        "container_definitions": "[{\"name\":\"${local.project_name}\",\"image\":\"${aws_ecr_repository.main.repository_url}:latest\",\"essential\":true,\"portMappings\":[{\"containerPort\":80,\"protocol\":\"tcp\"},{\"containerPort\":3000,\"protocol\":\"tcp\"}],\"logConfiguration\":{\"logDriver\":\"awslogs\",\"options\":{\"awslogs-group\":\"${aws_cloudwatch_log_group.ecs.name}\",\"awslogs-region\":\"us-east-1\",\"awslogs-stream-prefix\":\"ecs\"}},\"environment\":[{\"name\":\"NODE_ENV\",\"value\":\"production\"}]}]",
        "tags": {
          "Name": "${local.project_name}-task"
        }
      }
    },
    "aws_lb": {
      "main": {
        "name": "${local.project_name}-alb",
        "internal": false,
        "load_balancer_type": "application",
        "security_groups": [
          "${aws_security_group.alb.id}"
        ],
        "subnets": [
          "${aws_subnet.public_1.id}",
          "${aws_subnet.public_2.id}"
        ],
        "enable_deletion_protection": false,
        "enable_http2": true,
        "tags": {
          "Name": "${local.project_name}-alb"
        }
      }
    },
    "aws_lb_target_group": {
      "main": {
        "name": "${local.project_name}-tg",
        "port": 80,
        "protocol": "HTTP",
        "vpc_id": "${aws_vpc.main.id}",
        "target_type": "ip",
        "deregistration_delay": 30,
        "health_check": {
          "enabled": true,
          "healthy_threshold": 2,
          "unhealthy_threshold": 3,
          "timeout": 5,
          "interval": 30,
          "path": "/",
          "protocol": "HTTP",
          "matcher": "200-299"
        },
        "tags": {
          "Name": "${local.project_name}-tg"
        }
      }
    },
    "aws_lb_listener": {
      "http": {
        "load_balancer_arn": "${aws_lb.main.arn}",
        "port": 80,
        "protocol": "HTTP",
        "default_action": [
          {
            "type": "redirect",
            "redirect": {
              "port": "443",
              "protocol": "HTTPS",
              "status_code": "HTTP_301"
            }
          }
        ]
      },
      "https": {
        "load_balancer_arn": "${aws_lb.main.arn}",
        "port": 443,
        "protocol": "HTTPS",
        "ssl_policy": "ELBSecurityPolicy-TLS-1-2-2017-01",
        "certificate_arn": "arn:aws:acm:us-east-1:${data.aws_caller_identity.current.account_id}:certificate/REPLACE_WITH_YOUR_CERTIFICATE_ARN",
        "default_action": [
          {
            "type": "forward",
            "target_group_arn": "${aws_lb_target_group.main.arn}"
          }
        ]
      }
    },
    "aws_ecs_service": {
      "main": {
        "name": "${local.project_name}-service",
        "cluster": "${aws_ecs_cluster.main.id}",
        "task_definition": "${aws_ecs_task_definition.main.arn}",
        "desired_count": 2,
        "launch_type": "FARGATE",
        "platform_version": "LATEST",
        "scheduling_strategy": "REPLICA",
        "deployment_minimum_healthy_percent": 100,
        "deployment_maximum_percent": 200,
        "health_check_grace_period_seconds": 60,
        "network_configuration": {
          "subnets": [
            "${aws_subnet.private_1.id}",
            "${aws_subnet.private_2.id}"
          ],
          "security_groups": [
            "${aws_security_group.ecs.id}"
          ],
          "assign_public_ip": false
        },
        "load_balancer": [
          {
            "target_group_arn": "${aws_lb_target_group.main.arn}",
            "container_name": "${local.project_name}",
            "container_port": 80
          }
        ],
        "deployment_circuit_breaker": {
          "enable": true,
          "rollback": true
        },
        "tags": {
          "Name": "${local.project_name}-service"
        },
        "depends_on": [
          "aws_lb_listener.http",
          "aws_lb_listener.https"
        ]
      }
    },
    "aws_appautoscaling_target": {
      "ecs": {
        "max_capacity": 10,
        "min_capacity": 2,
        "resource_id": "service/${aws_ecs_cluster.main.name}/${aws_ecs_service.main.name}",
        "scalable_dimension": "ecs:service:DesiredCount",
        "service_namespace": "ecs"
      }
    },
    "aws_appautoscaling_policy": {
      "cpu": {
        "name": "${local.project_name}-cpu-autoscaling",
        "policy_type": "TargetTrackingScaling",
        "resource_id": "${aws_appautoscaling_target.ecs.resource_id}",
        "scalable_dimension": "${aws_appautoscaling_target.ecs.scalable_dimension}",
        "service_namespace": "${aws_appautoscaling_target.ecs.service_namespace}",
        "target_tracking_scaling_policy_configuration": {
          "predefined_metric_specification": {
            "predefined_metric_type": "ECSServiceAverageCPUUtilization"
          },
          "target_value": 70,
          "scale_in_cooldown": 300,
          "scale_out_cooldown": 60
        }
      },
      "memory": {
        "name": "${local.project_name}-memory-autoscaling",
        "policy_type": "TargetTrackingScaling",
        "resource_id": "${aws_appautoscaling_target.ecs.resource_id}",
        "scalable_dimension": "${aws_appautoscaling_target.ecs.scalable_dimension}",
        "service_namespace": "${aws_appautoscaling_target.ecs.service_namespace}",
        "target_tracking_scaling_policy_configuration": {
          "predefined_metric_specification": {
            "predefined_metric_type": "ECSServiceAverageMemoryUtilization"
          },
          "target_value": 80,
          "scale_in_cooldown": 300,
          "scale_out_cooldown": 60
        }
      }
    },
    "aws_cloudfront_distribution": {
      "main": {
        "enabled": true,
        "is_ipv6_enabled": true,
        "comment": "CloudFront distribution for ${local.project_name}",
        "default_root_object": "index.html",
        "price_class": "PriceClass_100",
        "origin": [
          {
            "domain_name": "${aws_lb.main.dns_name}",
            "origin_id": "alb",
            "custom_origin_config": {
              "http_port": 80,
              "https_port": 443,
              "origin_protocol_policy": "http-only",
              "origin_ssl_protocols": [
                "TLSv1.2"
              ],
              "origin_read_timeout": 60,
              "origin_keepalive_timeout": 5
            }
          }
        ],
        "default_cache_behavior": {
          "allowed_methods": [
            "DELETE",
            "GET",
            "HEAD",
            "OPTIONS",
            "PATCH",
            "POST",
            "PUT"
          ],
          "cached_methods": [
            "GET",
            "HEAD"
          ],
          "target_origin_id": "alb",
          "viewer_protocol_policy": "redirect-to-https",
          "compress": true,
          "forwarded_values": {
            "query_string": true,
            "cookies": {
              "forward": "all"
            },
            "headers": [
              "Host",
              "Origin",
              "Accept",
              "Accept-Language",
              "Accept-Encoding"
            ]
          },
          "min_ttl": 0,
          "default_ttl": 3600,
          "max_ttl": 86400
        },
        "restrictions": {
          "geo_restriction": {
            "restriction_type": "none"
          }
        },
        "viewer_certificate": {
          "cloudfront_default_certificate": true
        },
        "custom_error_response": [
          {
            "error_code": 404,
            "response_code": 200,
            "response_page_path": "/index.html",
            "error_caching_min_ttl": 300
          },
          {
            "error_code": 403,
            "response_code": 200,
            "response_page_path": "/index.html",
            "error_caching_min_ttl": 300
          }
        ],
        "tags": {
          "Name": "${local.project_name}-cloudfront"
        }
      }
    }
  },
  "output": {
    "ecr_repository_url": {
      "description": "ECR Repository URL",
      "value": "${aws_ecr_repository.main.repository_url}"
    },
    "alb_dns_name": {
      "description": "Application Load Balancer DNS Name",
      "value": "${aws_lb.main.dns_name}"
    },
    "cloudfront_domain_name": {
      "description": "CloudFront Distribution Domain Name",
      "value": "${aws_cloudfront_distribution.main.domain_name}"
    },
    "cloudfront_distribution_id": {
      "description": "CloudFront Distribution ID",
      "value": "${aws_cloudfront_distribution.main.id}"
    },
    "ecs_cluster_name": {
      "description": "ECS Cluster Name",
      "value": "${aws_ecs_cluster.main.name}"
    },
    "ecs_service_name": {
      "description": "ECS Service Name",
      "value": "${aws_ecs_service.main.name}"
    },
    "vpc_id": {
      "description": "VPC ID",
      "value": "${aws_vpc.main.id}"
    }
  }
}